# Generated by Django 5.2 on 2025-10-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_product_image_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
